FILES = Server.py  filters.py \
    base.html  dataset_files.html datasets.html named_queries.html named_query.html query.html show_file.html



build:	$(SERVER_DIR)
	cp $(FILES) $(SERVER_DIR)
	
$(SERVER_DIR):
	mkdir -p $@
