FILES = \
    metacat \
    metacat_ui.py metacat_config.py  \
    metacat_auth.py metacat_dataset.py metacat_query.py token_lib.py metacat_file.py \
	metacat_admin.py

build:	$(UI_DIR)
	cp $(FILES) $(UI_DIR)
	
$(UI_DIR):
	mkdir -p $@
