#!/bin/env python

from metacat_config import MetaCatConfig
import sys, getopt, os

Usage = """
Usage: metacat [-c <config file>] list <list options>

Configuration file can also be specified using environment variable METACAT_CONFIG
"""

opts, args = getopt.getopt(sys.argv[1:], "?c:", ["--help"])
opts = dict(opts)
#print(opts)

if len(args) < 1 or "--help" in opts or "-?" in opts:
    print(Usage)
    sys.exit(2)

cfg_file = opts.get("-c", os.environ.get("METACAT_CONFIG"))
if not cfg_file:
    print(Usage)
    sys.exit(2)

#print("cfg_file")
config = MetaCatConfig(cfg_file)
    
cmd, args = args[0], args[1:]

if cmd == "list":
    from metacat_list import do_list
    do_list(config, args)
else:
    print(Usage)
    sys.exit(2)
    
    
